version: '3.7'
services:
  mongodb:
    build: ./mongodb
    image: tms-mongodb/mongo:latest
    container_name: tms-mongo-mongo

  back:
    build: ./back
    image: tms-mongodb/back:latest
    container_name: tms-mongodb-back
    environment:
      - NODE_ENV=production
      - TMS_APP_NAME=tms-mongo-web
      - TMS_APP_PORT=3000
      - TMS_FINDER_FS_ROOTDIR=/storage
      - TMS_FINDER_FS_OUTDIR=/storage
      - TMS_FINDER_FS_CUSTOMNAME=true
      - TMS_APP_LOG4JS_LEVEL=debug
      - TMS_MONGODB_HOST=localhost
      - TMS_MONGODB_PORT=27017
      - TMS_MONGODB_USER=root
      - TMS_MONGODB_PASSWORD=root
      - TMS_REDIS_PREFIX=dev-op
      - TMS_REDIS_HOST=localhost
      - TMS_REDIS_PORT=6378
      - TMS_REDIS_EXPIRESIN=7200
      - TMW_API_HOST=http://localhost
      - TMW_API_PORT=3000
      - TMW_REQUIRE_BUCKET=
      - TMS_PLUGINS_IT_IP=
    command:
      [
        'sh',
        './wait-for.sh',
        'mongodb:27017',
        '-t',
        '300',
        '--',
        'node',
        'server',
      ]
  ue_admin:
    build:
      context: ./ue_admin
      args:
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
        vue_app_base_url: /admin
        vue_app_back_auth_base: /auth
        vue_app_back_api_base: /api
        vue_app_back_api_plugin: /plugin
        vue_app_back_api_fs: /fs
        vue_app_front_doceditor_add: ''
        vue_app_front_doceditor_modify: ''
    image: tms-mongodb/ue-admin:latest
    container_name: tms-mongodb-ue_admin
    environment:
      - NGINX_WEB_BASE_URL=/admin

  ue_mongo:
    build:
      context: ./ue_mongo
      args:
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
        vue_app_base_url: /mongo
        vue_app_back_auth_base: /auth
        vue_app_back_api_base: /api
        vue_app_back_api_plugin: /plugin
        vue_app_back_api_fs: /fs
        vue_app_front_doceditor_add: ''
        vue_app_front_doceditor_modify: ''
        vue_app_front_batcheditor: ''
        vue_app_plugin_bucket:'web'
    image: tms-mongodb/ue-mongo:latest
    container_name: tms-mongodb-ue_mongo
    environment:
      - NGINX_WEB_BASE_URL=/mongo
